---

- name: "Ensure epel-release is installed"
  become: true
  package:
    name: "{{ epel_package_name }}"
    state: "{{ epel_package_state }}"
  register: "_epel_repo"
  tags: ["epel"]


- name: "Import EPEL RPM GPG Key"
  become: true
  rpm_key:
    key: "{{ epel_key_url }}"
  retries: 5
  delay: 30
  when: "_epel_repo.changed"
  tags: ["epel"]


- name: "Clean Yum Cache"
  become: true
  command: "/usr/bin/yum clean all"
  args:
    warn: false
  when: "_epel_repo.changed"
  tags: ["epel"]


- name: "Refresh Yum Cache"
  become: true
  command: "/usr/bin/yum makecache"
  args:
    warn: false
  when: "_epel_repo.changed"
  tags: ["epel"]
