---
-
  name: "Ensure epel-release is installed"
  become: true
  ansible.builtin.package:
    name: "{{ epel_package_name }}"
    state: "{{ epel_package_state }}"
  register: "_epel_repo"
  tags: ["epel"]
-
  name: "Import EPEL RPM GPG Key" # noqa: no-handler
  when: "_epel_repo.changed"
  become: true
  ansible.builtin.rpm_key:
    key: "{{ epel_key_url }}"
  retries: 5
  delay: 30
  tags: ["epel"]
-
  name: "Clean Cache" # noqa: no-handler no-changed-when
  when: "_epel_repo.changed"
  become: true
  ansible.builtin.command: "/usr/bin/yum clean all"
  tags: ["epel"]
-
  name: "Refresh Cache" # noqa: no-handler no-changed-when command-instead-of-module
  when: "_epel_repo.changed"
  become: true
  ansible.builtin.command: "/usr/bin/yum makecache"
  tags: ["epel"]
