---

- name: "Converge"
  hosts: "all"
  tasks:
    - name: "Include cornfeedhobo.epel"
      ansible.builtin.include_role:
        name: "cornfeedhobo.epel"
      vars:
        epel_install: true
        epel_configure: true
        epel_extra_packages: ["jq"]
