# {{ item.name }}

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN set -ex && \
{% if item.name == 'centos-7' %}
	yum makecache && \
	yum --assumeyes install \
		python3 \
		python3-devel \
{% elif item.name == 'centos-stream' %}
	dnf makecache && \
	dnf --assumeyes install \
		python \
		python-devel \
		python3-dnf \
{% endif %}
		bash \
		iproute \
		sudo
