---

dependency:
  name: "galaxy"

driver:
  name: "docker"

platforms:
  - name: "molecule-almalinux"
    image: "docker.io/almalinux:9"
    commands:
      - "dnf makecache"
      - >-
          dnf --assumeyes install
          bash
          iproute
          python3-devel
          sudo

provisioner:
  name: "ansible"

verifier:
  name: "ansible"
