---
-
  name: "Verify"
  hosts: "all"
  gather_facts: true
  tasks:
    -
      name: "Include role variables"
      ansible.builtin.include_vars: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"
    -
      name: "Get the epel package status"
      ansible.builtin.package:
        name: "{{ epel_package_name }}"
      check_mode: true
      diff: true
      register: "_epel_packages"
    -
      name: "Assert that epel is already installed"
      ansible.builtin.assert:
        that:
          - "not _epel_packages.changed"
